### PR TITLE
Spelling: A module has crashed

### PR DESCRIPTION
**Pull request by comradekingu**
The?

### CODE REVIEW

**Comment by TheLastProject** [comment]
It's displayed in the module's tab, like with the last screenshot about updating. Maybe "This module has crashes" but then it seems weird that the other is "Updating module" instead of "This module is updating"

**Comment by comradekingu** [comment]
It could be either "Module crashed" or "* module (has) crashed".
"Module has crashed" is a marked noun error.

**Comment by TheLastProject** [comment]
Both strings are displayed in the same location as in the screenshot in below comment and refer to the module themselves. So yeah, it's not "A module has crashed" but I can't really decide on what grammatically correct option sounds best. I'll just go with whatever your suggestion will be.

https://github.com/Pext/Pext/pull/296#issuecomment-612656667

**Comment by comradekingu** [comment]
Can it crash before the updating?

**Comment by TheLastProject** [comment]
They are two different states that never happen at the same time but are simply displayed in the same location because both situations cause the module to be unavailable

**Comment by TheLastProject** [comment]
Because a picture says more than a thousand words:
Screenshot 2020-04-16 at 11 41 27
Screenshot 2020-04-16 at 13 16 04

**Pull request merged**
