### PR TITLE
Pext: Updates for assets used in README

### PR DESCRIPTION
**Pull request by theimpulson**
- Dependency on images from website is dropped. Instead images are converted into GIF and are linked in README. Makes README a bit smaller and cool.
- Also assets used in README have been moved to a new dir called 'assets' to reduce clutter in root dir of source

### CODE REVIEW

**Comment by TheLastProject** [comment]
You should also move and fix the symlink to logo.png in docs to not break the documentation on ReadTheDocs.

I agree the GIF looks better, but could you maybe include a script somewhere so the GIF can be easily updated if the screenshots on the website get updated?

**Comment by theimpulson** [comment]
I am unable to find any reference to logo.png in ReadTheDocs. Do you mean the reference in .reuse/dep5 ?

**Comment by TheLastProject** [comment]
In the docs directory there is a symlink called logo.png. The docs include the readme, so an assets symlink needs to be created in docs which points to the other assets directory

**Comment by theimpulson** [comment]
Is it fine now? Also about generating new GIFs, its pretty easy. You need imagemagick for that. This is the command for I used for an example: `convert -delay 100 pext-*.PNG -loop 0 pext_intro.gif`.

Adding a script for a simple command doesn't seems to be a good idea. However, in case required, maybe a comment can be added before the GIF in README.

**Comment by TheLastProject** [comment]
Maybe put the script in RELEASE_STEPS.MD so I won't forget to update the screenshots each release.

Yeah, you should indeed update the dp5 file

**Comment by theimpulson** [comment]
Updated dp5 file and added instructions in RELEASE_STEPS.MD as well

**Comment by TheLastProject** [comment]
The dp5 change is not quite right, only the logo is copyright White Paper Fox, not everything in that directory

**Comment by theimpulson** [comment]
Fixed

**Pull request merged**
