### PR TITLE
New method for command argument handling

### PR DESCRIPTION
**Pull request by ata2001**
This commit finally fixes handling of multi-word commands

### CODE REVIEW

**Comment by TheLastProject** [comment]
Thanks for this! I like the changes and the ideas, it feels a lot cleaner. However, it sadly does cause a few regressions:
- If you type the name of the command correctly, it will always be at the end of the list, thus meaning I can no longer type "git" in the pass module to run the git command, as I have a password named "GitHub". I'm thinking we probably want to always make Ctrl+Enter run the first command in the list if no command is selected? See screenshot:
screenshot_20190112_184632
- Just pressing Enter on a command doesn't pass any args anymore, not even an empty list, causing module breakage:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sylvia/.config/pext/modules/pext_module_pass/__init__.py", line 293, in selection_made
    if self.settings['_api_version'] >= [0, 8, 0] and selection[0]["args"]:
KeyError: 'args'
```
- Could you please document Ctrl+Return in the README with the other keys?
- I don't see any way to run a command with arguments with a mouse click, but thinking of that, that was never working before. I'll probably make that activate on right-click myself after this change :)

**Comment by ata2001** [comment]
> Thanks for this! I like the changes and the ideas, it feels a lot cleaner. However, it sadly does cause a few regressions:
> 
> * If you type the name of the command correctly, it will always be at the end of the list, thus meaning I can no longer type "git" in the pass module to run the git command, as I have a password named "GitHub". I'm thinking we probably want to always make Ctrl+Enter run the first command in the list if no command is selected? 

I think jumping to another entry would be confusing when someone accidentally presses Ctrl+Enter while trying to select an entry that does not accept arguments. Also we can't know for sure if the user is searching for a command when they're typing in a search string that matches entries of both types. I can think of three different solutions/workarounds to this issue.

1. Always put commands on top
2. create a custom sorting algorithm, that puts results, that match the search string on the start of the string, to the first places on the list
3. tab complete only to entries that match the search strings on the start of the string

> * I don't see any way to run a command with arguments with a mouse click, but thinking of that, that was never working before. I'll probably make that activate on right-click myself after this change :)

right click opens the context menu currently, I don't know what should it be mapped to

**Comment by TheLastProject** [comment]
> I think jumping to another entry would be confusing when someone accidentally presses Ctrl+Enter while trying to select an entry that does not accept arguments. Also we can't know for sure if the user is searching for a command when they're typing in a search string that matches entries of both types. I can think of three different solutions/workarounds to this issue.

Fair, but I'm actually thinking of a fourth one. We could probably prefix the UI entries with the ⏎ and ^⏎ symbols to indicate what Enter and what Ctrl+Enter would toggle?

**Comment by TheLastProject** [comment]
Looking great, just one last thing!

Could you change the "Current entry is not a command" to "No command available for current filter" or something similar? Because Ctlr+Enter will run even if it's not the current entry.

**Comment by TheLastProject** [comment]
Thank you so much! :)

**Pull request merged**
