### PR TITLE
Check for pip problems only in Debian Strech and below.

### PR DESCRIPTION
**Pull request by wodend**
Sorry if this doesn't follow guidelines, I didn't have chance to review all of the developer documentation yet.
Just suggesting a quick fix for issue #322.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Ah, I wasn't aware you were trying to take this on yourself too. Your code does make sense to me and is more consistent with the previous version of the code, only excluding Debian 10, not pre-9 versions too. I am willing to merge this if you can fix the merge conflict.

**Comment by TheLastProject** [comment]
I've prefixed the title of this PR with WIP because the merge didn't go right, so I can keep better track of what is mergeable. Feel free to change the title back once you get it working :)

**Comment by TheLastProject** [comment]
You removed your own code while merging. If you look at the files tab, you will see that this PR no longer contains any code changes whatsoever :)

**Comment by wodend** [comment]
Thanks for letting me know that was silly, I was too tired making that change.

**Comment by TheLastProject** [comment]
Thanks :)

**Pull request merged**
