### PR TITLE
Spelling: Loadable\, previously loaded -module.

### PR DESCRIPTION
**Pull request by comradekingu**
(On the assumption that this is correct)
Also, is it not "super" instead of "meta"?

### CODE REVIEW

**Comment by TheLastProject** [comment]
>(On the assumption that this is correct)

Well, "loading" under Pext means "opening a new tab", into which the module gets loaded. "Load module" is therefore also bound to `Ctrl+T`. Modules keep running in the background so each tab is always a loaded module.

Here is a screenshot of the menu for clarity: 
Screenshot 2019-07-09 at 09 36 09

May be worth removing "loaded" though. Just "Switch to next module" and "Switch to previous module"? Seeing as it refers to the open tabs and people may recognize `Ctrl+Tab`, it may be clear enough in the shorter version?

>Also, is it not "super" instead of "meta"?

Qt wants me to use Meta as name, if I'll use Super it won't recognize it. It's later in the file used with .nativeText anyway, which generates text (or icons) that looks correct for whatever platform Pext is running on.

Anyway, closing this because "next loadable" is definitely not correct in Pext's context.

**Comment by comradekingu** [comment]
@TheLastProject
That makes very little sense to me. The notion that it is already loaded, when switching to it is important why?
"Loaded" confuses me. Especially with "Previous loaded", in my head that is "previously loaded", which must mean there is a current module, in between that and the next one.
Also, next is before previous, I would want it to be the other way around.
As the menu already says "Module", how about just
Next
Previous
Reload
Close
Load
Manage
Install

**Comment by TheLastProject** [comment]
Well, "Manage" is for multiple modules at the same time, so I don't think we can just remove the word Module. "Next module" and "Previous module" seems quite fine to me though, feel free to simplify that.

**Comment by comradekingu** [comment]
"Management"?
It doesn't have to be super simple though, one improvement is already an improvement.

**Comment by TheLastProject** [comment]
Sure, sounds good to me.

**Comment by TheLastProject** [comment]
So... what's the plan now?

**Pull request closed without merging**
