### PR TITLE
Relicense documentation under CC BY-SA 4.0

### PR DESCRIPTION
**Pull request by TheLastProject**
Because of issue #66, I realized it makes more sense to relicense the documentation from GPLv3+ to CC BY-SA 4.0, to simplify collaboration and make it easier to legally reuse it on other websites. I've also explicitly added the screenshots as artwork for the same reason.

I've going to need an okay for this relicense from the following people, as they contributed to at least one file that would change license:
@step21 
@Jookia 
@hous3m4ster 
@kozross 

A simple "I'm okay with this" will do. Thanks in advance, all of you!

### CODE REVIEW

**Comment by kozross** [comment]
I have no problem with this change - in fact, I support it.

**Comment by step21** [comment]
Tbh, any 'problems' with GPL v3 are probably way overstated in that issue.
But whatever, I don't care if you change the license.

**Comment by hous3m4ster** [comment]
Fine by me ;)

**Comment by Jookia** [comment]
I don't support this change as it makes transfer of documentation between source code and official documentation require relicensing between GPLv3+ and CC-BY-SA 4.0. That said, I'm not going to block it. You can use my changes under CC-BY-SA 4.0.

Additionally I waive copyright for my tiny (uncopyrightable?) two lines of documentation, so it may be used under any license or no license.

**Pull request merged**
