### PR TITLE
Spelling: Install modules

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by TheLastProject** [comment]
I'm not sure if this is better? It seems more logical to say "only continue if" than "don't continue if" to me, especially because the dialog it is shown in has a positive action (install) and not a negative one (delete)

**Comment by comradekingu** [comment]
@TheLastProject It is much shorter, and gets to the same point.
English is a language with a clear negative bias in its structure, and does not carry over negative sentiment the same way.
"Continue …" begs the question of what it is that needs continuation.
I think the bigger change is not breaking the 4th wall.

**Comment by TheLastProject** [comment]
Fair point. I'll wait with this until after the 0.14 release though, because it'll break existing translations.

**Comment by TheLastProject** [comment]
https://github.com/comradekingu/Pext/blob/a4562980784caf2d2e439b1beaab3c95e2f3b147/pext/qml/InstallModuleFromURLDialog.qml#L51 contains the same string. Probably should be changed there too.

**Comment by TheLastProject** [comment]
I'm sorry for being so late to mention this, but I've been thinking about using the string "Only install modules from people you trust". It's even shorter, simpler and less technical. What do you think?

**Comment by comradekingu** [comment]
@TheLastProject Sure, very nice and wholesome feel to it. The notion that developers are people is actually beneficial in the context.

**Comment by TheLastProject** [comment]
Oh, for the future, please don't change the branch to merge into. i18n is managed by Weblate. Having things go to i18n instead of master creates a lot of extra work for me.

**Comment by comradekingu** [comment]
@TheLastProject Sorry about that, it is the one linked to next to the strings on WL, don't know if that can be differantiated there.

**Comment by TheLastProject** [comment]
Understandable, I'll try to look at it when I find the time. Also, thanks for the pull request!

**Pull request merged**
