### PR TITLE
Fix Windows shortcut (#220)

### PR DESCRIPTION
**Pull request by TangentFoxy**
By installing for all users instead of just the administrator.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Is this ready to be merged? You were asking about how to test this in an issue so I want to make sure before I hit merge. If not, please prefix the title of this pull request with "WIP: "

**Comment by TangentFoxy** [comment]
> You were asking about how to test this in an issue

Yes, I still have no idea how.

> Is this ready to be merged?

Yes.

**Comment by TheLastProject** [comment]
If you make a pull request (like this one) it'll build on Travis and AppVeyor automatically. It's not perfect but it's the easiest way to test. Has this been tested yet?

**Comment by recursiveribbons** [comment]
Tested build, OK.

**Pull request merged**
