### PR TITLE
Fix ui module packaging

### PR DESCRIPTION
**Pull request by ph20**
python package after build doesn't contain `ui` module

### CODE REVIEW

**Comment by TheLastProject** [comment]
Just wondering, how are you testing these things? Just so I can test along with you.

**Comment by ph20** [comment]
Hi Sylvia,
I'm preparing python package and the try to setup it in clear virtual env

```
# build package
python setup.py build sdist

# install package
python3 -m venv pext-testenv
source pext-testenv/bin/activate
pip install dist/Pext-0.32-108-gd7faefc.tar.gz
pext-testenv/bin/pext
```

**Comment by TheLastProject** [comment]
Could you pull my master branch into your branch? The macOS build should probably be fixed there, would make it easier to test this.

**Comment by ph20** [comment]
Hi, yep. Let's see

**Comment by TheLastProject** [comment]
Hmm, that is odd, flake8 doesn't fail for me locally. Same 3.9.2 version :/

**Comment by TheLastProject** [comment]
Well, the code seems correct to me so I'm merging it anyway. Thanks :)

**Pull request merged**
