### PR TITLE
Set pidfile path for window and skip sigusr1 that windows doesn't support

### PR DESCRIPTION
**Pull request by step21**

### CODE REVIEW

**Comment by TheLastProject** [comment]
Hmm, I would prefer this to use tempfile.gettempdir() instead of 2 hardcoded directories, but most curiously, what about using signal.CTRL_BREAK_EVENT on Windows instead of signal.SIGINT1 as written in https://docs.python.org/3/library/signal.html#signal.signal? Does that make Pext currently unhide when someone tries to start it when already running? I haven't ever heard of Ctrl+Break being a common key combination to press on Windows in a terminal Windows (what is it even supposed to do?), so it doesn't sound like that'd cause trouble.

**Comment by step21** [comment]
Maybe this is better. I don't really know, CTRL_BREAK_EVENT can only be used with os.kill() though. Why not the windowstate thing I mentioned?

**Comment by TheLastProject** [comment]
Well, from my research Popen is to open new processes, but we already have one. I just can't see how to actually make that work, unless I'm misunderstanding Popen.

Also, if the signal method works, the code changes are extremely minimal, just ```signal.CTRL_BREAK_EVENT if os.name == 'nt' else signal.SIGUSR1``` (or in the more verbose if/else like you did) in two places, simply need to test if it works, because from how I read the documentation it should. The less difference between platforms, the easier to maintain.

**Comment by TheLastProject** [comment]
Ah, nevermind, that won't work:

Windows: The signal.CTRL_C_EVENT and signal.CTRL_BREAK_EVENT signals are special signals which can only be sent to console processes which share a common console window, e.g., some subprocesses.

https://docs.python.org/3/library/os.html.

If you can find another way, that'd be great, but for now I think this pull request is indeed the right way to do it, will probably merge after work.

**Comment by step21** [comment]
Well, I get that you want your code to be as easily portable as possible, but I guess this has to balanced against usefulness. I could not find a signal that does what you want - some mention that you can use sigkill and then try to catch it, but as was also said there that doesn't seem a very good idea (and would also add a lot of extra as you would then have a subprocess where this signal is processed)
If you do not want to access the native Windows APIs, there is a few other options. Or just leave it for now :)

I think this captures your use case very well maybe:
https://www.allegro.cc/forums/thread/602466

Or, though likely not ideal for you: Sockets, Pipes, or Files (polled periodically),  WCF (Windows Communication Foundation)/Windows messages (from here: https://social.msdn.microsoft.com/Forums/en-US/0a34baef-da6b-4d86-b10f-b48e08746c29/powershell-kill-sigusr1-pid?forum=winforms)
https://stackoverflow.com/questions/12520754/python-windows-popen-with-wshowwindow-in-startupinfo-not-affecting-display

**Comment by TheLastProject** [comment]
For now, I want to start off by merging this, so that Pext at least no longer crashes on Windows, especially because this feature is fairly minor.

However, the wshowwindow thing indeed sounds good, especially now I see people talk about second start. I just personally do not know how I would implement this because I have never used Popen in a way like that. Pipes indeed sound promising as well.

Polling files would not be reasonable because either the delay would be too long or (and) there would be a lot of unnecessary hard drive usage.

If you would have an implementation using Popen or pipes, I will definitely look into it, especially if there is any chance of having that code work on all platforms or if it's simply a reasonable amount of code. I'm mostly worried of having to add a lot of Windows-specific code that I won't be able to maintain.

**Comment by step21** [comment]
Sure. I don't have an implementation right now and haven't used it that way either, but maybe I'll look into it.

**Pull request merged**
