### PR TITLE
AppImage packaging

### LINKED ISSUE #22: Linux Packaging
Packaging Pext a bit better would be nice. It can already be installed under Linux just fine using setup.py, but on macOS, that support is very lacking. macOS support or maybe an AppImage or Snap or so would be awesome.

Edit: If you're here for Hacktoberfest, support for a single of the following formats would suffice:
macOS App
AppImage
Snap
Flatpak
Deb
RPM

Edit 2: title changed to Linux packaging because that's what's being done.

### LINKED ISSUE #25: CI support
Pext is long overdue on some CI. Travis is probably the most logical choice. Making sure Pext runs and the (code standard) tests are run would be the scope of this issue. Unfortunately we lack other unit tests.

### PR DESCRIPTION
**Pull request by TheAssassin**
This PR introduces a Travis CI configuration. It runs the tox tests, and if they pass, generates an AppImage and uploads it to transfer.sh.

To do:

  - Rebase and squash. Although I like the history (because it shows how much effort has been put into this), it might be worth rebasing this branch.
  - Replace upload to transfer.sh with [uploadtool](https://github.com/probonopd/uploadtool). Releases will be uploaded to GitHub releases, PR build files will be uploaded to transfer.sh. See the homepage for details.
  - Embed update information and upload `.zsync` files using uploadtool. This way, using AppImageUpdate, the users can enjoy the latest and greatest version of Pext.
  - Remove more unnecessary data. There's a lot of files which are of zero use for running the application. E.g., the `include` directory which is installed in the libgit2 step. Smaller AppImages make users happy.

It further contains some minor fixes. Feel free to commit to my branch to finish the feature.

This PR closes #22 and closes #25, at least for Linux.

### CODE REVIEW

**Comment by TheLastProject** [comment]
This pull request is amazing. However, just currently it doesn't start, because pygit2 is unable to locate libcurl-gnutls.so.4:
```
$ ./pext-x86_64\(3\).AppImage --profile=test
Traceback (most recent call last):
  File "/tmp/.mount_pext-xTcLEmo/usr/lib/python3.6/site-packages/Pext-0.9+dev-py3.6.egg/pext/pext.py", line 51, in <module>
    import pygit2
  File "/tmp/.mount_pext-xTcLEmo/usr/lib/python3.6/site-packages/pygit2-0.26.0-py3.6-linux-x86_64.egg/pygit2/__init__.py", line 32, in <module>
    from _pygit2 import *
ImportError: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```
The other features, especially uploadtool.sh, I will definitely add because that looks amazing. zsync seems like more work, but definitely cool as well. And yeah, definitely aware of the needed cleanups, 139MB is still rather big.

**Comment by TheLastProject** [comment]
Also, just to poke GitHub: For when this gets merged, it closes #25 as well :)

**Comment by TheAssassin** [comment]
Seems like we have to bundle this library.

> zsync seems like more work, but definitely cool as well.

AppImageUpdate support is fairly easy to implement. When using uploadtool (which creates a release with the same title on every new build), you have a pretty static URL which just needs to be embedded into the AppImage as "update information". The current version of AppImageUpdate even natively supports GitHub releases, so you just need to embed the following string:

```
gh-releases-zsync|Pext|Pext|continuous|Pext-x86_64.AppImage
```

This can be done by adding a flag to the appimagetool call:

```
appimagetool -u <my update ìnformation> [...]
```

As you see, it's fairly easy to implement.

**Comment by TheLastProject** [comment]
I messed this up a bit. I think you need to do the following:
```
git add upstream https://github.com/Pext/Pext
git fetch upstream
git rebase -i HEAD~59 --onto origin/master
```

Then, in the rebase, remove my commits: 25ab6da 348cd1f 54f18a2 f051af2 43dbddc and run the rebase.

I'm sorry.

**Comment by TheAssassin** [comment]
I fixed the build on the other, broken branch. It worked fine there (although CI builds failed, the packaging step worked, the work is still available [here](https://github.com/TheAssassin/Pext/tree/master-broken)).

In order to get in sync with this branch again, I checked out the new master, cherry-picked the few fixes I made apart from the Travis configuration, and then copied and re-committed the `.travis.yml` and the build script.

Let's see whether we'll end up with a working AppImage now.

By the way, the script `build-appimage.sh` is safe to run locally, it'll run the entire build process in an isolated temporary directory, it uses the repository directory only to install the Pext packages from.

**Comment by TheAssassin** [comment]
@TheLastProject added a dependency on the `pygit2` package in order to be able to run `setup.py`. This is really problematic, as people who do not yet have `pygit2` on their systems won't be able to install the package, which leads to awkward errors like the one in the build log. Please re-think the current implementation, I think the disadvantages clearly overweigh the advantages.

**Comment by TheLastProject** [comment]
You're totally right about the setup.py thing, fixed in https://github.com/Pext/Pext/commit/9534112c6e937d66e9c948132c65b70494c51590.

**Comment by TheAssassin** [comment]
Ok, after a _lot_ of fiddling we have a working AppImage! It needs to be tested on a few distros to make sure it will run, but it works fine so far on xubuntu xenial and Kubuntu 17.10 (live CD).

Try it out: https://transfer.sh/NZXAm/Pext-x86_64.AppImage

To Do:
  - split up into several stages again to make sure the AppImage won't be built if any of the test configurations fails (it's also far from perfect to build the AppImage in one of the "normal" test configurations)
  - test AppImage on different distros to ensure compatibility
  - embed update information once the release is uploaded to GitHub releases

**Feedback by Pext Linux users would be appreciated!**

**Comment by TheAssassin** [comment]
Ok, looks like I'm done.

**Comment by TheLastProject** [comment]
Unfortunately, there still seem to be SSL-related issues, at least on Fedora 26. I can't install or update modules, making Pext unfortunately unusable:

```
Traceback (most recent call last):
  File "/tmp/.mount_Pext-xw2xEvV/usr/lib/python3.6/site-packages/Pext-0.9+dev-py3.6.egg/pext/pext.py", line 1023, in install_module
    pygit2.clone_repository(url, os.path.join(self.module_dir, dir_name))
  File "/tmp/.mount_Pext-xw2xEvV/usr/lib/python3.6/site-packages/pygit2-0.26.0-py3.6-linux-x86_64.egg/pygit2/__init__.py", line 258, in clone_repository
    check_error(err)
  File "/tmp/.mount_Pext-xw2xEvV/usr/lib/python3.6/site-packages/pygit2-0.26.0-py3.6-linux-x86_64.egg/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: user cancelled certificate check
```

**Comment by TheAssassin** [comment]
I'll increase the verbosity of my cURL patch, and test the resulting AppImage on Fedora 26.

**Comment by TheAssassin** [comment]
Finally getting somewhere here. See https://travis-ci.org/TheAssassin/Pext/jobs/303347448#L1793-L1802. The AppImage is building fine, and now, we have a new error (well, that's progress, too). The error seems related to #35. @TheLastProject I hope you can provide some information whether it's the same bug. (I hope so actually, because that'd mean my work would be mostly done).

Some background information:

The build scripts now uses some patched Debian packages of (lib)curl I build on OBS [here](https://build.opensuse.org/package/show/home:TheAssassin:AppImageLibraries/curl-httponly). They contain the patch previously contained in this repository. By adding the repository to a system and upgrading (lib)curl packages, one can make use of them. I don't recommend usage on normal systems (their SSL CA path detection is called every time a request is made, but that's not necessary on a normal system), but they're fine for building AppImages with.

Any developer building AppImages and having a dependency on libcurl should be able to make use of them. It was quite some work to get them to work in this generic way, but I think it was worth the effort. The challenge was a great opportunity to get myself into Debian packaging further that I didn't seek for but am happy to have gone through.

I hope I can make a release quality patch and have cURL merge it.

**Comment by TheAssassin** [comment]
Adapted the PR. UI seems to work as expected. #39 needs to be merged before continuing work on this PR.

Unfortunately, the Python binary seems to lack SSL support, which is quite annoying.

```
./Pext-x86_64.AppImage --install-module=https://github.com/Pext/pext_module_emoji 
.../work/Pext/pext/__main__.py:44: UserWarning: Module pext was already imported from None, but .../work/Pext is being added to sys.path
  from pkg_resources import parse_version
⇩ emoji (https://github.com/Pext/pext_module_emoji)
⇩ emoji: <urlopen error unknown url type: https>
Traceback (most recent call last):
  File ".../work/Pext/pext/__main__.py", line 1049, in install_module
    porcelain.clone(UpdateManager.fix_git_url_for_dulwich(url), os.path.join(self.module_dir, dir_name))
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/site-packages/dulwich/porcelain.py", line 310, in clone
    progress=errstream.write)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/site-packages/dulwich/client.py", line 363, in fetch
    progress)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/site-packages/dulwich/client.py", line 1398, in fetch_pack
    b"git-upload-pack", url)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/site-packages/dulwich/client.py", line 1282, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/site-packages/dulwich/client.py", line 1261, in _http_request
    resp = self.opener.open(req)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/urllib/request.py", line 549, in _open
    'unknown_open', req)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/tmp/.mount_Pext-.../usr/lib/python3.6/urllib/request.py", line 1388, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

Probably an issue with Miniconda. Further investigation required.

**Comment by TheAssassin** [comment]
Following a hit of @TheLastProject and combining what my knowledge about SSL certificate path issues across desktop Linux distributions, I was able to add some code to the AppRun script that inspects the system for a usable SSL certificate bundle in some known locations. I did the same for libcurl, which we needed to work with HTTPS cross-distro, and I distribute this library on [OBS](https://build.opensuse.org/package/show/home:TheAssassin:AppImageLibraries/curl-httponly).

I hope that this *finally* fixes the SSL related issues, so that we can release an AppImage after almost 3 months of development and 3 months of planning ahead of that, making this 6 months of work.

**Comment by TheAssassin** [comment]
@TheLastProject so far so good, merged the latest changes. However, there's an issue with the "AppImage test" (that is, installing an example plugin). Could you please have a look at https://travis-ci.org/TheAssassin/Pext/jobs/360496439#L1926 and tell me how to fix it (or just commit the fix to my repo)? Thanks.

**Comment by TheLastProject** [comment]
Cool to see you back here :)

You caught Pext right in the middle of a refactor, which made --install-module a bit more awful to use for now (a proper fix is planned soon). I pushed the correct way to do it for now to your master branch :)

**Comment by TheAssassin** [comment]
Thanks, @TheLastProject. Actually, specifying _something_ worked fine for my tests. I debugged the issue we had in January and it seems like a library conflict (of a library that is `dlopen()ed`). Otherwise, it works fine now.

**Comment by TheAssassin** [comment]
@TheLastProject I think the package building needs to be moved to the script section. In `after_success`, the build won't fail if the packaging fails. Therefore it's almost impossible to detect failures.

**Comment by TheLastProject** [comment]
Sounds good to me

**Comment by TheAssassin** [comment]
@TheLastProject the AppImage works! Running the latest build on my Ubuntu 16.04 system at the moment.

I think this needs some more testing (as the dependencies aren't copied completely any more), but yeah, it works fine. The package installation works fine, no SSL issues, etc.

**Comment by TheLastProject** [comment]
It works on my Fedora install with no issues as well. The file is still rather large but honestly it seems fine to turn this into the official Linux AppImage then. At least just for nightly builds.

I'm glad you managed to figure this out :)

Would you mind terribly if I'd squash everything? Assuming you feel it is ready to be merged now?

**Comment by TheLastProject** [comment]
Would it soften the wound if I tweet on @PextTool's Twitter about it and explicitly thank you with a link to your GitHub in the tweet and CHANGELOG for the AppImage build? I get not wanting them squashed, but they are mostly test commits, so it doesn't make much sense to keep them in the history.

**Comment by TheAssassin** [comment]
@TheLastProject oh well, you can squash it, no problem, really. I was just kidding.

**Comment by TheAssassin** [comment]
Tests finished on Tumbleweed, Fedora, Antergos, Ubuntu bionic. This PR can be squashed & merged.

Yay! After 8-9 months of work.

**Comment by TheAssassin** [comment]
P.S.: Regarding the squash: The commit history helped in packaging some other software, seeing why some decisions have been made has been valuable information. But I will push the history as a new branch to my repository, then we can get it from there.

**Comment by TheLastProject** [comment]
That's fair. Can I just squash and merge it now? You can probably just push your master to a new branch on your fork right?

**Comment by TheAssassin** [comment]
Yes, that's the plan. As said in my previous comment, you can merge this now.

**Comment by TheAssassin** [comment]
Now we just need a tweet about the brand new AppImage. And maybe some optimizations, size wise.

**Comment by TheLastProject** [comment]
https://twitter.com/PextTool/status/980126739501379584 :)

**Pull request merged**
