### PR TITLE
Improve AppImage

### PR DESCRIPTION
**Pull request by TheAssassin**
This PR shall:

  - reduce the AppImage size
  - add features to the AppImage
  - add support for AppImageUpdate

Please do not merge until further notice.

### CODE REVIEW

**Comment by TheAssassin** [comment]
https://github.com/Pext/Pext/pull/94/commits/a909bee34546c4ec88279aa8f86353d0684184ad is more of an experiment, and needs some further testing.

**Comment by TheLastProject** [comment]
Just to make sure, I should make sure a "latest" tag always refers to the latest stable whenever I make a new release?

**Comment by TheLastProject** [comment]
@probonopd stated the following in https://github.com/AppImage/appimage.github.io/pull/473:

```

**Comment by TheAssassin** [comment]
> Just to make sure, I should make sure a "latest" tag always refers to the latest stable whenever I make a new release?

That's what `latest` does, pre-releases are not considered.. See https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases.

**Comment by TheAssassin** [comment]
> I'm not quite sure. I see a delete_blacklisted step in https://github.com/Pext/Pext/blob/master/travis/build-appimage.sh#L57 so I assume this was not intentional?

The libraries are in a directory `delete_blacklisted` doesn't consider.
See my comment in the other issue. I don't think there's any harm in bundling this special libstdc++. The miniconda team probably know what they're doing. We might even break miniconda by deleting this library, as we don't control the version.

**Comment by TheLastProject** [comment]
>That's what latest does, pre-releases are not considered. See https://github.com/AppImage/AppImageSpec/blob/master/draft.md#github-releases.

Ah, that's great! Do you feel I could already merge this part? Including native AppImage updating support and including the appdata.xml is already a great improvement. Can create a new pull request later for removing useless files step-by-step.

>The libraries are in a directory delete_blacklisted doesn't consider.
>See my comment in the other issue. I don't think there's any harm in bundling this special libstdc++. The miniconda team probably know what they're doing. We might even break miniconda by deleting this library, as we don't control the version.

Yup, I saw it, thanks for the confirmation :)

**Comment by TheAssassin** [comment]
Sure, let's merge it.

**Pull request merged**
